project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: hpc.qmd
        text: "1. Getting HPC Access"
      - text: "2. Workspace Curation"
        menu:
        - text: "Admin Role"
          href: setup_admin.html
        - text: "Launch Role"
          href: setup_participant.html
      - href: pipeline.qmd
        text: "3. Adding Pipelines"
      - href: workflow.qmd
        text: "4. Running a Workflow"
    cookie-consent: 
      type: express
      style: simple
      palette: light
      policy-url: https://www.sydney.edu.au/privacy-statement.html
    google-analytics: "G-TNWWV3HK57"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


