project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: hpc.qmd
        text: "HPC Access"
      - text: "Setup"
        menu:
        - text: "Owner"
          href: setup_admin.html
        - text: "Participant"
          href: setup_participant.html
      - href: pipeline.qmd
        text: "Adding Pipelines"
      - href: workflow.qmd
        text: "Running a Workflow"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


