project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: About
      - href: setup.html
        text: "Setup"
      - text: "Use-Cases"
        menu:
        - text: "Example 1"
          href: notebooks/01a-fundamentals.html
        - text: "Example 2"
          href: notebooks/01b_exampleRcontent.html
        - text: "Example 3"
          href: notebooks/01c_exampleMDcontent.html

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


