project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: hpc.qmd
        text: "1. Getting HPC Access"
      - text: "2. Workspace Curation"
        menu:
        - text: "As an Admin"
          href: setup_admin.html
        - text: "As a Participant"
          href: setup_participant.html
      - href: pipeline.qmd
        text: "3. Adding Pipelines"
      - href: workflow.qmd
        text: "4. Running a Workflow"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


