project:
  type: website
  output-dir: docs

website:
  title: "SIH User Guides"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/hpc.qmd
        text: "1. Getting HPC Access"
      - text: "2. Workspace Curation"
        menu:
        - text: "Admin Role"
          href: notebooks/setup_admin.html
        - text: "Launch Role"
          href: notebooks/setup_participant.html
      - href: notebooks/pipeline.qmd
        text: "3. Adding Pipelines"
      - href: notebooks/workflow.qmd
        text: "4. Running a Workflow"
    cookie-consent: 
      type: express
      style: simple
      palette: light
      policy-url: https://www.sydney.edu.au/privacy-statement.html
    google-analytics: "G-TNWWV3HK57"

  body-footer: "<div style='font-size: 14px;'>All materials copyright Sydney Informatics Hub, University of Sydney</div>"

format:
  html:
    theme: 
      light: flatly
    css: styles.scss
    toc: true
    code-overflow: scroll
    highlight-style: github
    page-layout: full


